
/* quantidade vendida por sabor-ano de 2016*/
SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON
TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY  TP.SABOR, YEAR(NF.DATA_VENDA)
ORDER BY SUM(INF.QUANTIDADE) DESC; 

/* calculando a qtd total de 2016 - de todos os sabores*/
SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO=INF.NUMERO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY YEAR(NF.DATA_VENDA);

/*juntando as tabelas para calcular o percentual de participaçaõ de cada sabor*/
SELECT VENDA_SABOR.SABOR, VENDA_SABOR.ANO, VENDA_SABOR.QUANTIDADE, 
((VENDA_SABOR.QUANTIDADE/VENDA_TOTAL.QUANTIDADE)*100) AS PERCENTUAL FROM
(SELECT TP.SABOR, YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON
TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY  TP.SABOR, YEAR(NF.DATA_VENDA)) AS VENDA_SABOR
INNER JOIN
(SELECT YEAR(NF.DATA_VENDA) AS ANO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM tabela_de_produtos TP
INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
INNER JOIN notas_fiscais NF ON NF.NUMERO=INF.NUMERO
WHERE YEAR(NF.DATA_VENDA)=2016
GROUP BY YEAR(NF.DATA_VENDA)) AS VENDA_TOTAL
ON VENDA_SABOR.ANO=VENDA_TOTAL.ANO
ORDER BY VENDA_SABOR.QUANTIDADE DESC;


